### ISSUE TITLE
使用说明站点似乎挂了

### ISSUE THREAD

**Issue by yllhwa** [YuehaiTeam/cocogoat-client#1]
浏览不了，我看了下全国的ping都是超时，应该是挂了(

**Comment by xytoki** [comment]
实际上是因为README写了但是使用说明还没做（  
项目刚开始，功能都还有一些欠缺，暂时还没有特别多精力写文档，等制作完了再上线。看来得先把链接撤掉。

**Comment by yllhwa** [comment]
thx. 用ocr识别的方法，这应该也是顶流了。
