### ISSUE TITLE
关于识别的问题（重复识别？多引擎交叉识别？等）

### ISSUE THREAD

**Issue by QAQQL** [YuehaiTeam/cocogoat-client#11]
小建议:
1.对爆红的词条进行double check ,两次识别,实在不行再调用百度ocr[手动滑稽]
2.增加(识别错误时)遇到爆红词条暂停自动选择录入,修改成功后手动恢复自动录入的快捷键,现在的~是停止,不是暂停,遇到错误手改有好几条还是反应不过来(间隔时间已经调至3s)

ps:
我有个暴击率+8.9%的识别了n次老是是18.9%,建议查查字库
![图片](https://user-images.githubusercontent.com/51136763/114898996-31c72980-9e45-11eb-913f-19be46a13c68.png)
![图片](https://user-images.githubusercontent.com/51136763/114899162-4dcacb00-9e45-11eb-9a61-6575ce44eec1.png)

**Comment by xytoki** [comment]
我们自己测试来看，出错的重复识别还是会出错，置信度也不会变化。多个引擎交叉识别后面可能会加入。
至于修正，后续会在仓库里做疑似有误的展示和保留截图，这个比加大延迟靠谱也更方便。
最后前面多一个1这个是个已知问题...现在还在努力调训练集，如果真的调不出来可能就换ocr引擎了。

**Comment by QAQQL** [comment]
哈哈哈哈哈,好的,辛苦作者大大

**Comment by xytoki** [comment]
在仓库里做疑似有误的展示和保留截图的相关是 #2 ，预计在下个版本更新就会加上，到时候可以不用暂停，全部识别完之后回到仓库批量纠正。因为我们识别是想往队列方向做，现在同步识别效率还是略微有些低的

**Comment by QAQQL** [comment]
嗯,对识别置信度低的圣遗物保存截图,标记flag,全部识别后到主界面自行处理

**Comment by kdays** [comment]
能否先截图 全部截图结束后再进行批量的ocr?
不然ocr时间意外的长 =v=b

**Comment by xytoki** [comment]
> 能否先截图 全部截图结束后再进行批量的ocr?
> 不然ocr时间意外的长 =v=b

队列确实有在考虑了，不过我们这现在有更换ocr引擎的想法，所以可能会稍微迟一些推出。

**Comment by xytoki** [comment]
我们会在0.4.1更换OCR为PaddleOCR并做一些针对性的优化，从目前的测试来看更换后识别错误率应该会降低很多。

**Comment by xytoki** [comment]
0.4.1已发，由于识别速度已经提高太多，队列暂时不是很有必要了。这条暂时关闭，如有其他问题可以重开。
