### ISSUE TITLE
识别暴击头出错问题

### ISSUE THREAD

**Issue by Narcissus1st** [YuehaiTeam/cocogoat-client#17]
![image](https://user-images.githubusercontent.com/82761975/115145926-cf5d6b80-a086-11eb-85e3-e30513f2c09a.png)
![image](https://user-images.githubusercontent.com/82761975/115145930-dedcb480-a086-11eb-8d54-056977175c29.png)
识别暴击头的时候数值出现错误

**Comment by xytoki** [comment]
这个已经在 https://github.com/YuehaiTeam/cocogoat/commit/17d7816fee6a1ab8bf979493a553bb9a862cf625 修复了，可以下载测试版试试看，或者等明天早上新版本更新。
