### ISSUE TITLE
建议增加记住识别框的窗口位置与大小这一功能

### ISSUE THREAD

**Issue by Sakurakouji-Runa** [YuehaiTeam/cocogoat-client#18]
我使用1600*900分辨率，每次打开识别框后都需要花时间调整窗口大小和位置，希望识别框每次被打开时都处于上次的大小和位置。

**Comment by Sakurakouji-Runa** [comment]
还有圣遗物切换器也是，每次都要重新调整大小和位置

**Comment by xytoki** [comment]
感谢建议，这个已经在准备了。
(PS.目前应该默认大小就是1600x900 100%缩放的才对

**Comment by Sakurakouji-Runa** [comment]
> 感谢建议，这个已经在准备了。
> (PS.目前应该默认大小就是1600x900 100%缩放的才对

P.S. 不巧我用的是125%缩放😂

**Comment by xytoki** [comment]
已经加上，会在下一次发版时进入正式版。
