### ISSUE TITLE
手动点击识别圣遗物所有星级都识别为一星

### ISSUE THREAD

**Issue by hrukalive** [YuehaiTeam/cocogoat-client#27]
(v0.4.4) 点击开始时的识别没有出现问题，再次手动点击右上角识别后星级错误。所有圣遗物都识别为一星，是否是哪里API变动却没有处理识别按钮的流程。

![image](https://user-images.githubusercontent.com/7337458/117019331-ed4be280-acba-11eb-8e94-200f00e9c0a7.png)

**Comment by xytoki** [comment]
大概率是那个tooltip遮挡识别区了。可以用暂时快捷键win+`代替识别按钮，后续会修。

**Comment by hrukalive** [comment]
确实，用快捷键就没问题了。
