### ISSUE TITLE
对接Genshin Optimizer

### ISSUE THREAD

**Issue by Mr-Quin** [YuehaiTeam/cocogoat-client#28]
希望加入导出到 [Genshin Optimizer](https://frzyc.github.io/genshin-optimizer/#/) 的功能

Genshin Optimizer 的 [JSON 格式](https://github.com/Mr-Quin/mona_to_go/blob/main/tests/goDump.json) （artifactDatabase的部分）

导出工具我试着写了一个 https://github.com/Mr-Quin/mona_to_go 提供参考

**Comment by xytoki** [comment]
GO的对接之前有跟他们联系过，他们那边已经写了莫娜的格式的导入了（ https://github.com/3096/genshin-optimizer/ ）但是没有合并进主分支，所以我们这在那边有消息之前暂时不会直接做格式转换。

**Comment by Mr-Quin** [comment]
原来如此

**Comment by xytoki** [comment]
GO那边对接估计还需要一段时间，所以就先用你这个库做了一下GO的导出( 524c37b0d7a124f6a4f0112971bf979ce8a1d8fc )。

**Comment by Mr-Quin** [comment]
谢谢
