### ISSUE TITLE
0.4.4自动切换时经常主属性识别异常

### ISSUE THREAD

**Issue by Jiacheng-z** [YuehaiTeam/cocogoat-client#29]
目前使用的是窗口化. 0.4.4自动切换时, 主属性经常识别疑似异常, 甚至主属性会识别错误, 例如给沙漏识别生命4780. (已取消加速滚动)
手动单点切换识别时间较长, 但识别率更高.

**Comment by xytoki** [comment]
试一下0.4.5，有对这块的一个bug做了修复，不知道你这个问题是不是同一个原因。如果试了还不行的话我再查查。最近另一位没空，所以总是一不小心把有bug的就发出去了...
