### ISSUE TITLE
在性能较低设备上会出现漏识别的情况

### ISSUE THREAD

**Issue by zyr17** [YuehaiTeam/cocogoat-client#37]
在30帧、MX250的垃圾笔记本上用的时候有时候会出现切换器点击后识别到的仍是前一个圣遗物的情况。

将`src/ArtifactSwitch/App.vue`的`sleepRatio = 3`并重新编译后就基本不会出现了。肉眼看了一段时间没有发现出错，最后统计的时候仓库685个识别到665个，没有仔细check是同样问题漏了还是某些圣遗物被当成相同的筛掉了/识别失败了。

因为不会写UI所以只能开个issue了= =请问能否将该参数作为设置中可调整参数？

另一种设想的解决方案是对于连续识别到相同圣遗物的情况特殊处理，只不过好像会和当前的识别终止逻辑有冲突（现在是4次相同就停止识别的样子？），可能得和自动切换器识别到的圣遗物位置联动来推测是识别完了还是识别漏了。

**Comment by xytoki** [comment]
收到，自动判断响应时间已经在准备了，下个版本应该会上。

> 只不过好像会和当前的识别终止逻辑有冲突（现在是4次相同就停止识别的样子？）  

四次停止是手柄模拟模式下的停止逻辑，鼠标模式是用滚动判断的。

**Comment by xytoki** [comment]
949a4e6232a4eefce8e0e265d610d035bf89e0e2 中彻底改了识别等待的逻辑，现在应该不会再因为等待时间太短的原因漏了，先close，如果还有漏可以reopen
