### ISSUE TITLE
20210725, 打不开占卜铺?

### ISSUE THREAD

**Issue by sirius0xff** [YuehaiTeam/cocogoat-client#39]
今天突然打不开,  页面空白一遍
昨天还好好的
是因为网站挂了吗?  
https://www.mona-uranai.com/

![cocogoat-v0 4 7-win64-rel2105201725_2021-07-25_14-30-30](https://user-images.githubusercontent.com/32758498/126889994-7abe0312-6574-4b68-9ee1-80f170e688d2.png)

**Comment by xytoki** [comment]
占卜铺的问题可以去 https://github.com/wormtql/genshin_artifact 咨询 （
具体打不开的原因应该是他们那边的问题 和我们关系不大
