### ISSUE TITLE
Translations not populating & non-i18n strings

### ISSUE THREAD

**Issue by rikai** [YuehaiTeam/cocogoat-client#41]
The following lines in the EN translation do not get translated despite having translations in en.json:
https://github.com/YuehaiTeam/cocogoat/blob/fa34615da4e85bd50d9aae34bf2f135c34df1a39/src/i18n/locales/en.json#L109-L113

As can be seen here:
![image](https://user-images.githubusercontent.com/515221/130207785-0208d366-7c45-4ae7-a6d9-a6b8c8665cfd.png)

Additionally, are there any plans to expand i18n to other parts of the application such as the optimize interface? I know that certain parts are beyond your control as Mona's Divination Shop is embedded but for example,

https://github.com/YuehaiTeam/cocogoat/blob/524c37b0d7a124f6a4f0112971bf979ce8a1d8fc/src/App/Views/Frames/MonaFrame.vue#L48-L49

could easily be translated to:

"Mona's Divination Shop (Developed & Authorized by @wormtql)"

and https://github.com/YuehaiTeam/cocogoat/blob/524c37b0d7a124f6a4f0112971bf979ce8a1d8fc/src/App/Views/Frames/MonaFrame.vue#L54

to:
"Knocking on the door of an astrologer prodigy..."

This would at least give English users an idea of what this section is, even if we can not make use of it.

**Comment by rikai** [comment]
Exploring the app further, I have found additional untranslated strings. It seems that many of the options in the recognize interface do not seem to be translated as can be seen here:
![image](https://user-images.githubusercontent.com/515221/130208882-f4b14962-e644-4022-bc06-3b8971a844cd.png)

Despite being in the [en_artifacts.json translation file](https://github.com/YuehaiTeam/cocogoat/blob/main/src/i18n/locales/en_artifacts.json)

**Comment by xytoki** [comment]
Thanks for suggestions. Many translations are not in v0.4.7 yet, you can try testing versions in GitHub Actions (e.g. https://github.com/YuehaiTeam/cocogoat/actions/runs/1134031920).

**Comment by xytoki** [comment]
In fact there're still some untranslated strings in the latest testing version. We'll fix all of them in the v0.5.0 release together with English recognization.

**Comment by rikai** [comment]
I submitted PR #42 to attempt to assist in this process. Hopefully this is helpful to you folks!

I may submit some grammatical/phrasing updates in a separate PR as well.

**Comment by xytoki** [comment]
Thanks for PR :D
For translation errors, you can also use this POEditor link: https://poeditor.com/join/project?hash=jZiEtV01OO
Translations there will be synced before each release.

**Comment by rikai** [comment]
Thank you for the pointer! I think in this case it made sense to submit a PR as it added additional things beyond the translation. However, I have applied for English access for the future!

**Comment by xytoki** [comment]
The PRs are all merged and a new testing version with full English recognization support has been built (https://github.com/YuehaiTeam/cocogoat/actions/runs/1155554275). I think this issue can be safely closed now, and you can reopen it or post a new one if there're any other questions.

**Comment by rikai** [comment]
Just wanted it quickly point this out as I didn't want to create a full PR for what's probably a quick fix. One of the translations is still not populating and I believe it's because I did not prefix the line with a : [here](                    placeholder="__('圣遗物')").

My apologies!
