### ISSUE TITLE
好兄弟，你的海染套呢

### ISSUE THREAD

**Issue by aqiu817** [YuehaiTeam/cocogoat-client#60]
![截图](https://user-images.githubusercontent.com/19250671/144607137-ae92307b-75e9-464f-b427-4e57ff133c25.png)

**Comment by xytoki** [comment]
在 36b4580a48f508bc37eaf801e59c08248dc162aa 已经添加，需要下载测试版。
没发布正式版是因为目前各种效果都太差了，而我又没有大量时间优化识别部分，所以建议使用天目或者yas来识别。
